require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const compression = require('compression');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const app = express();
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(compression());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
const limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 1000, validate: { xForwardedForHeader: false } });
app.use(limiter);
app.use(express.static('public'));
// Models
const userSchema = new mongoose.Schema({ username: { type: String, required: true, unique: true, trim: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true }, role: { type: String, default: 'user', enum: ['user', 'moderator', 'admin'] }, status: { type: String, default: 'active', enum: ['active', 'banned', 'suspended'] }, createdAt: { type: Date, default: Date.now }, lastLogin: { type: Date } });
userSchema.pre('save', async function(next) { if (!this.isModified('password')) return next(); const salt = await bcrypt.genSalt(10); this.password = await bcrypt.hash(this.password, salt); next(); });
userSchema.methods.comparePassword = async function(pwd) { return await bcrypt.compare(pwd, this.password); };
userSchema.methods.toJSON = function() { const obj = this.toObject(); delete obj.password; return obj; };
const User = mongoose.model('User', userSchema);
const Message = mongoose.model('Message', new mongoose.Schema({ content: { type: String, required: true }, author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, channel: { type: String, default: 'general' }, isSticky: { type: Boolean, default: false }, createdAt: { type: Date, default: Date.now } }));
const Ban = mongoose.model('Ban', new mongoose.Schema({ target: { type: String, required: true }, reason: { type: String, default: '' }, bannedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, createdAt: { type: Date, default: Date.now }, expiresAt: { type: Date } }));
const Channel = mongoose.model('Channel', new mongoose.Schema({ name: { type: String, required: true, unique: true }, description: { type: String, default: '' }, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, createdAt: { type: Date, default: Date.now } }));
const PublishSettings = mongoose.model('PublishSettings', new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true }, siteUrl: { type: String, default: '' }, whitelistEnabled: { type: Boolean, default: false }, whitelist: { type: String, default: '' }, useSSL: { type: Boolean, default: false }, securityTag: { type: String, default: '' }, updatedAt: { type: Date, default: Date.now } }));
const Theme = mongoose.model('Theme', new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true }, name: { type: String, default: 'My custom CSS' }, css: { type: String, default: '' }, preset: { type: Number, default: -1000 }, updatedAt: { type: Date, default: Date.now } }));
const LayoutSettings = mongoose.model('LayoutSettings', new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true }, width: { type: Number, default: 400 }, height: { type: Number, default: 400 }, formHeight: { type: Number, default: 107 }, autoFormHeight: { type: Boolean, default: true }, adaptiveHeight: { type: Boolean, default: false }, formOnTop: { type: Boolean, default: false }, narrowLayout: { type: Boolean, default: false }, language: { type: String, default: 'ar' }, messagesPerPage: { type: Number, default: 20 }, sortDirection: { type: Number, default: 1 }, updatedAt: { type: Date, default: Date.now } }));
const IntegrationSettings = mongoose.model('IntegrationSettings', new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true }, privateKey: { type: String, required: true }, enabled: { type: Boolean, default: false }, autoRegister: { type: Boolean, default: false }, updatedAt: { type: Date, default: Date.now } }));
const RegUserSettings = mongoose.model('RegUserSettings', new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true }, regOnly: { type: Boolean, default: false }, selfReg: { type: Boolean, default: true }, authFacebook: { type: Boolean, default: false }, lastPostDel: { type: Boolean, default: false }, updatedAt: { type: Date, default: Date.now } }));
const registeredUserSchema = new mongoose.Schema({ owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, name: { type: String, required: true }, password: { type: String, required: true }, level: { type: Number, default: 2 }, voiced: { type: Boolean, default: false }, lastUsed: { type: Date }, lastIP: { type: String, default: '' }, registeredAt: { type: Date, default: Date.now } });
registeredUserSchema.pre('save', async function(next) { if (!this.isModified('password')) return next(); const salt = await bcrypt.genSalt(10); this.password = await bcrypt.hash(this.password, salt); next(); });
registeredUserSchema.methods.toJSON = function() { const obj = this.toObject(); delete obj.password; return obj; };
const RegisteredUser = mongoose.model('RegisteredUser', registeredUserSchema);
// Middleware
const authMiddleware = async (req, res, next) => { try { const token = req.headers.authorization?.split(' ')[1]; if (!token) return res.status(401).json({ success: false, error: 'No token' }); const decoded = jwt.verify(token, process.env.JWT_SECRET); const user = await User.findById(decoded.userId); if (!user) return res.status(401).json({ success: false, error: 'User not found' }); if (user.status !== 'active') return res.status(403).json({ success: false, error: 'Account not active' }); req.user = user; req.userId = user._id; next(); } catch (error) { return res.status(401).json({ success: false, error: 'Invalid token' }); } };
const adminMiddleware = (req, res, next) => { if (req.user.role !== 'admin') return res.status(403).json({ success: false, error: 'Admin access required' }); next(); };
const moderatorMiddleware = (req, res, next) => { if (!['admin', 'moderator'].includes(req.user.role)) return res.status(403).json({ success: false, error: 'Moderator access required' }); next(); };
// Auth APIs
app.post('/api/auth/signup', async (req, res) => { try { const { username, email, password } = req.body; if (!username || !email || !password) return res.status(400).json({ success: false, error: 'All fields required' }); if (password.length < 6) return res.status(400).json({ success: false, error: 'Password min 6 chars' }); const existing = await User.findOne({ $or: [{ email }, { username }] }); if (existing) return res.status(400).json({ success: false, error: 'Username/email exists' }); const user = new User({ username, email, password }); await user.save(); const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' }); res.status(201).json({ success: true, user: user.toJSON(), token }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/auth/login', async (req, res) => { try { const { username, password } = req.body; if (!username || !password) return res.status(400).json({ success: false, error: 'Username and password required' }); const user = await User.findOne({ $or: [{ username }, { email: username }] }); if (!user) return res.status(401).json({ success: false, error: 'Invalid credentials' }); const isMatch = await user.comparePassword(password); if (!isMatch) return res.status(401).json({ success: false, error: 'Invalid credentials' }); if (user.status !== 'active') return res.status(403).json({ success: false, error: 'Account not active' }); user.lastLogin = new Date(); await user.save(); const token = jwt.sign({ userId: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' }); res.json({ success: true, user: user.toJSON(), token }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.get('/api/auth/me', authMiddleware, (req, res) => { res.json({ success: true, user: req.user.toJSON() }); });
app.get('/api/auth/users', authMiddleware, adminMiddleware, async (req, res) => { try { const users = await User.find().sort({ createdAt: -1 }); res.json({ success: true, count: users.length, users }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/auth/users/:id/role', authMiddleware, adminMiddleware, async (req, res) => { try { const { role } = req.body; if (!['user', 'moderator', 'admin'].includes(role)) return res.status(400).json({ success: false, error: 'Invalid role' }); const user = await User.findByIdAndUpdate(req.params.id, { role }, { new: true }); if (!user) return res.status(404).json({ success: false, error: 'User not found' }); res.json({ success: true, user: user.toJSON() }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/auth/users/:id/status', authMiddleware, adminMiddleware, async (req, res) => { try { const { status } = req.body; const user = await User.findByIdAndUpdate(req.params.id, { status }, { new: true }); if (!user) return res.status(404).json({ success: false, error: 'User not found' }); res.json({ success: true, user: user.toJSON() }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.delete('/api/auth/users/:id', authMiddleware, adminMiddleware, async (req, res) => { try { const user = await User.findByIdAndDelete(req.params.id); if (!user) return res.status(404).json({ success: false, error: 'User not found' }); res.json({ success: true, message: 'User deleted' }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Messages
app.get('/api/messages', authMiddleware, async (req, res) => { try { const messages = await Message.find().populate('author', 'username role').sort({ createdAt: -1 }).limit(100); res.json({ success: true, count: messages.length, messages }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/messages', authMiddleware, async (req, res) => { try { const { content, channel, isSticky } = req.body; if (!content) return res.status(400).json({ success: false, error: 'Content required' }); const message = new Message({ content, author: req.userId, channel: channel || 'general', isSticky }); await message.save(); await message.populate('author', 'username role'); res.status(201).json({ success: true, message }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.delete('/api/messages/:id', authMiddleware, moderatorMiddleware, async (req, res) => { try { const message = await Message.findByIdAndDelete(req.params.id); if (!message) return res.status(404).json({ success: false, error: 'Message not found' }); res.json({ success: true, message: 'Message deleted' }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Bans
app.get('/api/bans', authMiddleware, moderatorMiddleware, async (req, res) => { try { const bans = await Ban.find().populate('bannedBy', 'username').sort({ createdAt: -1 }); res.json({ success: true, count: bans.length, bans }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/bans', authMiddleware, moderatorMiddleware, async (req, res) => { try { const { target, reason, expiresAt } = req.body; if (!target) return res.status(400).json({ success: false, error: 'Target required' }); const ban = new Ban({ target, reason: reason || '', bannedBy: req.userId, expiresAt: expiresAt ? new Date(expiresAt) : null }); await ban.save(); await ban.populate('bannedBy', 'username'); res.status(201).json({ success: true, ban }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.delete('/api/bans/:id', authMiddleware, moderatorMiddleware, async (req, res) => { try { const ban = await Ban.findByIdAndDelete(req.params.id); if (!ban) return res.status(404).json({ success: false, error: 'Ban not found' }); res.json({ success: true, message: 'Ban removed' }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Channels
app.get('/api/channels', authMiddleware, async (req, res) => { try { const channels = await Channel.find().populate('createdBy', 'username').sort({ createdAt: -1 }); res.json({ success: true, count: channels.length, channels }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/channels', authMiddleware, moderatorMiddleware, async (req, res) => { try { const { name, description } = req.body; if (!name) return res.status(400).json({ success: false, error: 'Channel name required' }); const existing = await Channel.findOne({ name }); if (existing) return res.status(400).json({ success: false, error: 'Channel exists' }); const channel = new Channel({ name, description: description || '', createdBy: req.userId }); await channel.save(); await channel.populate('createdBy', 'username'); res.status(201).json({ success: true, channel }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.delete('/api/channels/:id', authMiddleware, adminMiddleware, async (req, res) => { try { const channel = await Channel.findByIdAndDelete(req.params.id); if (!channel) return res.status(404).json({ success: false, error: 'Channel not found' }); res.json({ success: true, message: 'Channel deleted' }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Publish
app.get('/api/publish', authMiddleware, async (req, res) => { try { let settings = await PublishSettings.findOne({ user: req.userId }); if (!settings) { settings = new PublishSettings({ user: req.userId, securityTag: Math.random().toString(36).substring(2, 8).replace(/[uio]/g, 'x') }); await settings.save(); } res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/publish', authMiddleware, async (req, res) => { try { const { siteUrl, whitelistEnabled, whitelist, useSSL, securityTag } = req.body; let settings = await PublishSettings.findOne({ user: req.userId }); if (!settings) settings = new PublishSettings({ user: req.userId }); if (siteUrl !== undefined) settings.siteUrl = siteUrl; if (whitelistEnabled !== undefined) settings.whitelistEnabled = whitelistEnabled; if (whitelist !== undefined) settings.whitelist = whitelist; if (useSSL !== undefined) settings.useSSL = useSSL; if (securityTag !== undefined) settings.securityTag = securityTag; settings.updatedAt = new Date(); await settings.save(); res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/publish/generate-tag', authMiddleware, async (req, res) => { try { const tag = Math.round(Math.random() * 1838265624).toString(35).replace('u', 'z').replace('i', '5').replace('o', 'w'); res.json({ success: true, tag }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Theme
app.get('/api/theme', authMiddleware, async (req, res) => { try { let theme = await Theme.findOne({ user: req.userId }); if (!theme) { theme = new Theme({ user: req.userId, css: 'body { text-align: left; }' }); await theme.save(); } res.json({ success: true, theme }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/theme', authMiddleware, async (req, res) => { try { const { css, preset, name } = req.body; let theme = await Theme.findOne({ user: req.userId }); if (!theme) theme = new Theme({ user: req.userId }); if (css !== undefined) theme.css = css; if (preset !== undefined) theme.preset = preset; if (name !== undefined) theme.name = name; theme.updatedAt = new Date(); await theme.save(); res.json({ success: true, theme }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.get('/api/theme/presets', authMiddleware, async (req, res) => { try { const presets = [{ id: 13, name: 'Default blue', css: 'body { background: #f0f8ff; }' }, { id: 11, name: 'Basic transparent', css: 'body { background: transparent; }' }, { id: 1, name: 'Classic blue', css: 'body { background: #0066cc; color: white; }' }, { id: 2, name: 'Classic red', css: 'body { background: #cc0000; color: white; }' }, { id: 3, name: 'Classic yellow', css: 'body { background: #ffcc00; }' }, { id: 4, name: 'Classic light', css: 'body { background: #ffffff; }' }, { id: 5, name: 'Classic dark', css: 'body { background: #333333; color: white; }' }]; res.json({ success: true, presets }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Layout
app.get('/api/layout', authMiddleware, async (req, res) => { try { let settings = await LayoutSettings.findOne({ user: req.userId }); if (!settings) { settings = new LayoutSettings({ user: req.userId }); await settings.save(); } res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/layout', authMiddleware, async (req, res) => { try { const data = req.body; let settings = await LayoutSettings.findOne({ user: req.userId }); if (!settings) settings = new LayoutSettings({ user: req.userId }); Object.keys(data).forEach(key => { if (settings[key] !== undefined) settings[key] = data[key]; }); settings.updatedAt = new Date(); await settings.save(); res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Integration
app.get('/api/integration', authMiddleware, async (req, res) => { try { let settings = await IntegrationSettings.findOne({ user: req.userId }); if (!settings) { const privateKey = Math.random().toString(36).substring(2, 18).replace(/[^a-z0-9]/g, '').substring(0, 16); settings = new IntegrationSettings({ user: req.userId, privateKey }); await settings.save(); } res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/integration', authMiddleware, async (req, res) => { try { const { enabled, autoRegister } = req.body; let settings = await IntegrationSettings.findOne({ user: req.userId }); if (!settings) { const privateKey = Math.random().toString(36).substring(2, 18).replace(/[^a-z0-9]/g, '').substring(0, 16); settings = new IntegrationSettings({ user: req.userId, privateKey }); } if (enabled !== undefined) settings.enabled = enabled; if (autoRegister !== undefined) settings.autoRegister = autoRegister; settings.updatedAt = new Date(); await settings.save(); res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/integration/regenerate-key', authMiddleware, async (req, res) => { try { const newKey = Math.random().toString(36).substring(2, 18).replace(/[^a-z0-9]/g, '').substring(0, 16); let settings = await IntegrationSettings.findOne({ user: req.userId }); if (!settings) { settings = new IntegrationSettings({ user: req.userId, privateKey: newKey }); } else { settings.privateKey = newKey; } settings.updatedAt = new Date(); await settings.save(); res.json({ success: true, privateKey: newKey }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Registered User Settings
app.get('/api/registered-users/settings', authMiddleware, async (req, res) => { try { let settings = await RegUserSettings.findOne({ user: req.userId }); if (!settings) { settings = new RegUserSettings({ user: req.userId }); await settings.save(); } res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.put('/api/registered-users/settings', authMiddleware, async (req, res) => { try { const { regOnly, selfReg, authFacebook, lastPostDel } = req.body; let settings = await RegUserSettings.findOne({ user: req.userId }); if (!settings) settings = new RegUserSettings({ user: req.userId }); if (regOnly !== undefined) settings.regOnly = regOnly; if (selfReg !== undefined) settings.selfReg = selfReg; if (authFacebook !== undefined) settings.authFacebook = authFacebook; if (lastPostDel !== undefined) settings.lastPostDel = lastPostDel; settings.updatedAt = new Date(); await settings.save(); res.json({ success: true, settings }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Registered Users
app.get('/api/registered-users', authMiddleware, async (req, res) => { try { const { srch, srchin } = req.query; let query = { owner: req.userId }; if (srch && srchin) { if (srchin === 'nme') query.name = { $regex: srch, $options: 'i' }; else if (srchin === 'lastip') query.lastIP = { $regex: srch, $options: 'i' }; } const users = await RegisteredUser.find(query).sort({ registeredAt: -1 }); res.json({ success: true, count: users.length, users }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/registered-users', authMiddleware, async (req, res) => { try { const { uname, pword, lvl } = req.body; if (!uname || !pword) return res.status(400).json({ success: false, error: 'Name and password required' }); const existing = await RegisteredUser.findOne({ owner: req.userId, name: uname }); if (existing) return res.status(400).json({ success: false, error: 'Username exists' }); const level = parseInt(lvl) || 2; if (![2, 3, 4, 5].includes(level)) return res.status(400).json({ success: false, error: 'Invalid level' }); const user = new RegisteredUser({ owner: req.userId, name: uname, password: pword, level: level }); await user.save(); res.status(201).json({ success: true, user: user.toJSON() }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.post('/api/registered-users/bulk', authMiddleware, async (req, res) => { try { const { action, ids } = req.body; if (!action || !ids || !Array.isArray(ids)) return res.status(400).json({ success: false, error: 'Invalid request' }); switch (action) { case 'delete': const result = await RegisteredUser.deleteMany({ _id: { $in: ids }, owner: req.userId }); res.json({ success: true, message: 'Deleted ' + result.deletedCount + ' user(s)' }); break; case 'voice': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { voiced: true } }); res.json({ success: true, message: 'Voiced users' }); break; case 'unvoice': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { voiced: false } }); res.json({ success: true, message: 'Unvoiced users' }); break; case 'mod': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { level: 3 } }); res.json({ success: true, message: 'Mod status set' }); break; case 'unmod': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { level: 2 } }); res.json({ success: true, message: 'Mod status removed' }); break; case 'admin': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { level: 4 } }); res.json({ success: true, message: 'Admin status set' }); break; case 'unadmin': await RegisteredUser.updateMany({ _id: { $in: ids }, owner: req.userId }, { $set: { level: 2 } }); res.json({ success: true, message: 'Admin status removed' }); break; default: res.status(400).json({ success: false, error: 'Invalid action' }); } } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
app.delete('/api/registered-users/:id', authMiddleware, async (req, res) => { try { const user = await RegisteredUser.findOneAndDelete({ _id: req.params.id, owner: req.userId }); if (!user) return res.status(404).json({ success: false, error: 'User not found' }); res.json({ success: true, message: 'User deleted' }); } catch (error) { res.status(500).json({ success: false, error: error.message }); } });
// Health & Root
app.get('/api/health', (req, res) => { res.json({ success: true, message: 'NexusBox Backend is running', timestamp: new Date().toISOString(), database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected', version: '1.0.0' }); });
app.get('/', (req, res) => { res.json({ name: 'NexusBox API', version: '1.0.0', status: 'online' }); });
// Error handlers
app.use((err, req, res, next) => { console.error('Server error:', err); res.status(500).json({ success: false, error: 'Internal server error' }); });
app.use((req, res) => { res.status(404).json({ success: false, error: 'Endpoint not found' }); });
// Database & Start
async function connectToMongo() { try { await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000, socketTimeoutMS: 45000 }); console.log('✅ Connected to MongoDB Atlas'); } catch (error) { console.log('❌ MongoDB error:', error.message); setTimeout(connectToMongo, 5000); } }
const PORT = process.env.PORT || 3000;
connectToMongo();
app.listen(PORT, '0.0.0.0', () => { console.log('═══════════════════════════════════════'); console.log('🚀 NexusBox Backend Started!'); console.log('📡 Port: ' + PORT); console.log('═══════════════════════════════════════'); });
